#!/usr/bin/env python
import sys
import rospy
from ur5_kinematics.testing import PathTest
import argparse

if __name__ == '__main__':    
    rospy.init_node("kinematics_test", sys.argv)
    path = [
        [-0.3, -0.15, 0.35],
        [-0.3,  0.00, 0.40],
        [-0.3, 0.15, 0.35],
        [-0.45, 0.15, 0.30],
        [-0.6, 0.15, 0.35],
        [-0.6, 0.00, 0.40],
        [-0.6, -0.15, 0.35],
    ]
    parser = argparse.ArgumentParser()
    parser.add_argument('--type', '-t', default='real', choices=['real', 'simulated'])
    parser.add_argument('--prefix', '-p', default='')
    args = parser.parse_args()
    controller = '/scaled_pos_joint_traj_controller/follow_joint_trajectory'
    
    if args.type == 'simulated':
        print("Simulated environment...")
        controller = '/pos_joint_traj_controller/follow_joint_trajectory'
    test = PathTest(controller, '/kinematics_server/goal_pose', path, prefix=args.prefix, segment_duration=0.0)
    
    while True:
        test.update()